### ISSUE TITLE
Error message gate.be file in Berry scripting Console

### ISSUE THREAD

**Issue by TonyN26** [RPJacobs/CB19-GATE-CONTROL-SYSTEM#1]
I have a gate with a TMT show module. I would like to control the gate with an ESP32 with CP2102 for the same security reasons. I have Tasmota 13.4.0. installed, but I keep getting an error message when I enter the gate.be file into the Berry Scripting Console. I get the following error BRY: Exception> 'syntax_error' - input:27: strict: expression without side effect detected. How could I get the script to work? Thank you in advance.

**Comment by RPJacobs** [comment]
Why do you use a CP2102? Will build a new tasmota install and test this.

**Comment by RPJacobs** [comment]
I've managed to replicate the issue you're encountering with Tasmota version 13.4.0. It appears that this problem stems from a significant update introduced in version 13.0.0.1 (dated 2023-07-08), which affects how Berry scripts are interpreted:

In this update, Berry's import mechanism has been modified to enforce a 'strict' mode, which now identifies and flags expressions that have no side effects as errors (as per change #18997).

To resolve the error message you're seeing, you'll need to remove the line 27 in your script that reads print "connected MQTT". This line is being flagged as having no side effect, which is why the script fails to execute. Once you remove this line, your script should function correctly with your TMT gate module. I hope this helps, and thank you for reaching out for assistance.

**Comment by sfromis** [comment]
The Berry issue around that usage of `print` was not due to enforcing `strict`, but due to the syntax of `print "hello"` never being valid syntax in Berry. "Unfortunately", it did still work due to preparation for the added feature of Python-like f-strings (instead of needing to use `string.format`).

As f-strings instead became implemented in the parsing of Berry code, this unfinished syntax for calling a function with a string argument was removed again. Part of the reason is that it did not even work well for a `print`, as it did not work inside functions or with anything but a string argument.
